services:
    redis:
        image: redislabs/redismod
        container_name: redis
        ports:
            - '5000:5000'
    web:
            build: .
            container_name: web
            ports:
                - "8000:8000"
            volumes:
                - .:/app
            depends_on:
                - redis
